sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit
